### ISSUE TITLE
Fukuoka.go#2 + Fukuoka.rb LT大会

### ISSUE THREAD

**Issue by linyows** [fukuokago/event#2]
2014/08/21(木) 19:30 〜 21:30 
http://connpass.com/event/7559/

**Comment by linyows** [comment]
今回はfukuoka.rbと合同になりました〜
https://github.com/fukuokarb

**Comment by udzura** [comment]
よろしくお願いします :hamster:

**Comment by monochromegane** [comment]
## TODO
- [x] Fukuoka.rb と合同 + 7Fに変更になった旨を connpass 経由で通知
- [x] Fukuoka.rb と合同 + 7Fに変更になった旨を Facebookグループで通知
- [x] 7FはWifiがない旨を connpassに追記
- [x] 7Fの大きなホワイトボードを組み立てておく

## 当日の作業
- [x] パーティションの準備
- [x] プロジェクタを準備
- [x] 電源タップを準備
- [x] イスの搬入（7F用のイスが先に納品されれば不要）~~18日搬入とのこと~~
- [x] 案内板を設置する（8F->7Fも含む）

**Comment by linyows** [comment]
椅子は18日に届くので大丈夫そう

**Comment by monochromegane** [comment]
お、やった！ :smile:

**Comment by monochromegane** [comment]
告知系DONE

**Comment by linyows** [comment]
:+1:

**Comment by linyows** [comment]
残念ながら椅子の納品は翌週になったようです :crying_cat_face:

**Comment by linyows** [comment]
死霊〜death

| Title | Speaker |
| :-- | :-- |
| [ルビーストのためのGo](https://speakerdeck.com/linyows/go-for-rubyists) | @linyows |
| [Hello GoDoc!](http://www.slideshare.net/laco0416/hello-godoc-38209599) | @laco0416 |
| [最近やっていること](http://www.storyboards.jp/viewer/64t76r) | @udzura |
| [実践Go ツールの作成から配布まで](https://speakerdeck.com/monochromegane/shi-jian-go-turufalsezuo-cheng-karapei-bu-made) | @monochromegane |
| [gyowitter の ご紹介](https://speakerdeck.com/morygonzalez/gyowitter-falsegoshao-jie) | @morygonzalez |

**Comment by monochromegane** [comment]
speackerdeckに集約したいのでアップしなおしました

**Comment by morygonzalez** [comment]
アップロードしました。 [gyowitter のご紹介 // Speaker Deck](https://speakerdeck.com/morygonzalez/gyowitter-falsegoshao-jie)

**Comment by linyows** [comment]
あざす〜

**Comment by monochromegane** [comment]
Blogged: http://blog.monochromegane.com/blog/2014/08/23/fukuoka-go-2/
